version: "3"

services:
  activemq:
    build:
      args:
        http_proxy: http://192.168.0.37:707
        https_proxy: http://192.168.0.37:707
      context: ./
      dockerfile: Dockerfile
    image: lianshufeng/activemq
    ports:
      - "1883:1883"
      - "8161:8161"
      - "5672:5672"
      - "61613:61613"
      - "61614:61614"
      - "61616:61616"
    volumes:
      - ./conf:/opt/activemq/conf
      - ./data:/opt/activemq/data
    container_name: activemq
    restart: always

