version: "3"

services:
  activemq:
    image: registry.cn-chengdu.aliyuncs.com/1s/activemq
    ports:
      - "1883:1883"
      - "8161:8161"
      - "5672:5672"
      - "61613:61613"
      - "61614:61614"
      - "61616:61616"
    volumes:
#      - ${store}/data1/config:/opt/kafka/config
      - ./conf:/opt/activemq/conf
      - ./data:/opt/activemq/data
    container_name: activemq
    restart: always

