FROM lianshufeng/jdk:21

ENV FFMPEG_URL=https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz

RUN set -eux; \
    mkdir -p /tmp/ffmpeg && \
    curl -L "$FFMPEG_URL" -o /tmp/ffmpeg/ffmpeg.tar.xz && \
    tar -xJf /tmp/ffmpeg/ffmpeg.tar.xz -C /tmp/ffmpeg --strip-components=1 && \
    \
    # 只拷贝需要的二进制
    cp /tmp/ffmpeg/bin/ffmpeg /usr/local/bin/ && \
    cp /tmp/ffmpeg/bin/ffprobe /usr/local/bin/ && \
    chmod +x /usr/local/bin/ffmpeg /usr/local/bin/ffprobe && \
    \
    rm -rf /tmp/ffmpeg
