FROM lianshufeng/jdk:21

ENV FFMPEG_URL=https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz

RUN set -eux; \
    dnf install -y --setopt=install_weak_deps=False \
        curl \
        xz \
    && dnf clean all \
    && rm -rf /var/cache/dnf \
    \
    && mkdir -p /tmp/ffmpeg \
    && curl -L "$FFMPEG_URL" -o /tmp/ffmpeg/ffmpeg.tar.xz \
    && tar -xJf /tmp/ffmpeg/ffmpeg.tar.xz -C /tmp/ffmpeg --strip-components=1 \
    \
    && cp /tmp/ffmpeg/bin/ffmpeg /usr/local/bin/ \
    && cp /tmp/ffmpeg/bin/ffprobe /usr/local/bin/ \
    && chmod +x /usr/local/bin/ffmpeg /usr/local/bin/ffprobe \
    \
    && rm -rf /tmp/ffmpeg
