version: "3"

services:

  centos_vnc_chrome:
    build:
      # args:
        # http_proxy: http://192.168.31.222:707
        # https_proxy: http://192.168.31.222:707
      context: ./
      dockerfile: Dockerfile
      shm_size: 2gb
    shm_size: 2gb
    image: lianshufeng/centos_vnc_chrome
    ports:
      - "5901:5901"
      - "6901:6901"
    privileged: true
    container_name: centos_vnc_chrome
    restart: always
    environment:
      - VNC_PW=vncpassword
    
    
# http://192.168.80.128:6901/?password=vncpassword