version: "3"

services:
  kafka:
    image: lianshufeng/kafka
    ports:
      - "8822:22"
      - "9092:9092"
      - "2181:2181"
    volumes:
      - ${store}/data1/config:/opt/kafka/config
      - ${store}/data1/logs:/opt/kafka/logs
      - ${store}/data1/kafka_logs:/tmp/kafka-logs
    container_name: kafka
    restart: always
    environment:
      - KAFKA_LISTENERS=${KAFKA_HOST}:9092