version: "3"

services:
  kafka:
    image: registry.cn-chengdu.aliyuncs.com/1s/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    volumes:
#      - ${store}/data1/config:/opt/kafka/config
      - ./data/logs:/opt/kafka/logs
      - ./data/kafka_logs:/tmp/kafka-logs
    container_name: kafka
    restart: always
    environment:
      - KAFKA_LISTENERS=${KAFKA_HOST}:9092
      
      
      
      
#sudo firewall-cmd --add-port=2181/tcp --permanent 
#sudo firewall-cmd --add-port=9092/tcp --permanent 
#firewall-cmd --reload 
