version: "3"

services:

  ubuntu_vnc:
    build:
      # args:
        # http_proxy: http://192.168.31.98:1080
        # https_proxy: http://192.168.31.98:1080
      context: ./
      dockerfile: Dockerfile
      shm_size: 2gb
    shm_size: 2gb
    image: lianshufeng/ubuntu_vnc
    ports:
      - "4444:4444"
      - "7900:7900"
    privileged: true
    container_name: ubuntu_vnc
    restart: always
    environment:
      - VNC_PW=vncpassword
      - CHROME_CMD=www.baidu.com

    
# docker-compose down && docker-compose up --build    

# http://localhost:7900/?autoconnect=1&resize=scale&password=vncpassword
