version: "3"

services:

  ubuntu_vnc:
    build:
      # args:
        # http_proxy: http://192.168.31.98:1080
        # https_proxy: http://192.168.31.98:1080
      context: ./
      dockerfile: Dockerfile
      shm_size: 2gb
    shm_size: 2gb
    image: lianshufeng/ubuntu_vnc
    ports:
      - "5901:5901"
      - "6901:6901"
    privileged: true
    container_name: ubuntu_vnc
    restart: always
    environment:
      - VNC_PW=vncpassword
      - DEBUG=true
    
    
# http://192.168.31.132:6901/?password=vncpassword